### ISSUE TITLE
Clefspeare

### ISSUE THREAD

**Issue by pallebone** [pallebone/PersonalBlockListsPAllebone#1]
@Clefspeare13 I see your repo got disabled... will that be fixed at any point?

P

**Comment by pallebone** [comment]
@spirillen would you have any info on mypdns being offline?

**Comment by pallebone** [comment]
I found a way to log a ticket on your site so will close this issue.

**Comment by spirillen** [comment]
Hey @pallebone as you noticed your self then the Clefspeare13/porn-hosts suffered the same death as https://github.com/mypdns/porn-records did, in relation to that I do not trust github nor gitlab with any of my project data and this in combination with there anti privacy "policy" I have decided it was time to make the final move to mypdns.org for good.

You can read the issues related to making https://github.com/mypdns/porn-records available again in this open thread: https://mypdns.org/my-privacy-dns/porn-records/-/issues/1347

Since Clefspeare13 haven't been around for nearly 2 years, I have adopted it for good and made it available at https://mypdns.org/clefspeare13/pornhosts just as it was on GH, luckily I had the fully up to date git locally.

Please do spread the words in your circles, that the project didn't die, it just moved into a safer location.

**Comment by pallebone** [comment]
No problem. Thank you. I will fix this all with your help and get your sources listed as you suggest.

Will pickup the ticket on your side with regards to my being unable to access...

Thanks again :)

P

**Comment by spirillen** [comment]
Hey @pallebone 

Are you satisfied with the list combination? or do you have any suggestions for optimizing the lists?

**Comment by pallebone** [comment]
Hi @spirillen 

Everything is working and is good! No issues to report :)

Pete

**Comment by spirillen** [comment]
Glad to hear, then I have something to build on for the [Pi-hole list](https://github.com/pi-hole/pi-hole/issues/4431) I would make.

**Comment by pallebone** [comment]
@spirillen your DNS has no nameservers? Cant access website anymore?

**Comment by pallebone** [comment]
@spirillen I removed your lists as they no longer function or are maintained.

**Comment by spirillen** [comment]
@pallebone That's ok, As I'm out of funds and actually no longer have electrical power to host the project for now
